name: pokemon_card_grader
description: A Pokemon card condition grader and value estimator
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  http: ^1.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: PokemonSolid
      fonts:
        - asset: assets/fonts/pokemon_solid.ttf
    - family: PokemonHollow
      fonts:
        - asset: assets/fonts/pokemon_hollow.ttf
